# action.yaml
name: 'WP Version Bump Action'
description: 'Action to bump WordPress plugin/theme version '
author: 'Sixa'
branding:
  icon: chevron-right
  color: black
inputs:
  version:
    description: 'New version, should follow SemVer standard'
    required: true
  file_path:
    description: 'Relative path to the file to be modified'
    required: true
runs:
      using: 'node12'
      main: 'dist/index.js'

